### ISSUE TITLE
python版本怎么安装?

### ISSUE THREAD

**Issue by di-osc** [SunDoge/bytepiece-rs#6]
可以发布一个python包么,可以直接pip安装的

**Comment by SunDoge** [comment]
你可以在github action上下载编译好的，比如
https://github.com/SunDoge/bytepiece-rs/actions/runs/7960771826/artifacts/1256688874

我也可以发布到pypi，但是我还没确定名字，目前的包名是 bytepiece-py，不知道大家能不能接受。

**Comment by SunDoge** [comment]
@di-osc 已发布 https://pypi.org/project/bytepiece-py/
```
pip install bytepiece-py
```
